### ISSUE TITLE
불필요한 기능 & 질문

### ISSUE THREAD

**Issue by seongdohee** [mohwa/array-organizer#5]
type 정리하다가 굳이 없어도될것 같은 기능들이 있어서 이슈 올려봅니다.
이 함수들이 생기게 된 히스토리를 잘 몰라서 답변주시면 감사하겠습니다.

### fill, preInsert
iterable이 object형일때의 기능이 굳이 필요한지 의문점이 있습니다. 
{ k: 'z', v: 33' } 형태로 변환되는것도 좀 이상하다고 생각합니다.
```javascript
fill({ x: 11, y: 22, z: 33 }, 7, 0, 1); // [ 7, 7, {  k: 'z', v: 33 } ]
preInsert({ xx: 22, yy: 33 }, 3); // [3, { k: 'xx', v: 22 }, { k: 'yy', v: 33 }]
```

### search
아래의 예시를 보면 두번째 인자로 필요한 값을 가지고있는데, 굳이 search를 할 필요가 없습니다.
이 함수를 사용하려면 사용자는 이미 search한 값을 알고있어야 합니다. 
실제 검색기능을 구현하려면 `find` or `includes`을 사용하면 될 것 같습니다.
```javascript
search(['1', 2, 3], 3); // 3
```

**Comment by mohwa** [comment]
선 멋짐에 코멘트를 일단 남깁니다. 제대로 한듯한 느낌적 느낌이라 😀👍

**Comment by mohwa** [comment]
> fill, preInsert
iterable이 object형일때의 기능이 굳이 필요한지 의문점이 있습니다.

이런 경우도 있지않을까요? 🤔 

```javascript
preInsert({ xx: 11, yy: 22 }, { zz: 33 }, { xxx: 44 }); // [ { zz: 33 }, { xxx: 44 }, { k: 'xx', v: 11 }, { k: 'yy', v: 22 } ]

fill({ x: 11, y: 22, z: 33 }, { xx: 4 }, 0, 1); // [ { xx: 4 }, { xx: 4 }, { k: 'z', v: 33 } ]
```

또, 이 이슈는 `insert`, `replace` 함수에서도 나타나는 문제가 아닐까요? 🤔 

> { k: 'z', v: 33' } 형태로 변환되는것도 좀 이상하다고 생각합니다.

`key`, `value` 를 가진, `Map` 데이터인 경우, 반환된 배열에 값을 어떻게 채워넣을까? 고민한 결과였는데요, 

다시 생각해보니 `{ k: 'z', v: 33' }` 형태는 좀 이상한듯하네요.. 😢  

아래 같은 형태가 괜찮을듯한데 어떻게 생각하실까요? ❓ 

```javascript
preInsert({ xx: 11, yy: 22 }, { zz: 33 }, { xxx: 44 }); // [ { zz: 33 }, { xxx: 44 }, { xx: 11 }, { yy: 22 } ]
```

> search
아래의 예시를 보면 두번째 인자로 필요한 값을 가지고있는데, 굳이 search를 할 필요가 없습니다.
이 함수를 사용하려면 사용자는 이미 search한 값을 알고있어야 합니다.

내용이 잘 이해가 안가는데요, `search` 함수는 아래의 경우 사용될듯합니다.

```javascript
search(somethingValue, somethingValue 에서 찾으려는값)
```

> 실제 검색기능을 구현하려면 find or includes을 사용하면 될 것 같습니다.

네, 말씀주신것처럼, `find` 함수로도 구현 가능한 부분이지만, `find` 와  달리, 탐색을 위한 `callback` 을 제공하지않고, `단순 값`으로 사용할 수 있게 추가한 함수입니다. 🤔

**Comment by seongdohee** [comment]
> 또, 이 이슈는 insert, replace 함수에서도 나타나는 문제가 아닐까요? 🤔
{ k: 'z', v: 33' } 형태로 변환되는것도 좀 이상하다고 생각합니다.
key, value 를 가진, Map 데이터인 경우, 반환된 배열에 값을 어떻게 채워넣을까? 고민한 결과였는데요,
다시 생각해보니 { k: 'z', v: 33' } 형태는 좀 이상한듯하네요.. 😢
아래 같은 형태가 괜찮을듯한데 어떻게 생각하실까요? ❓

@mohwa 네 말씀해주신대로 insert, replace도 해당되네요 ㅎㅎ 제생각은 object 형태를 꼭 배열로 반환해야 할지 이것부터가 좀 고민이에요. 다같이 고민해보면 좋을것같아요

**Comment by seongdohee** [comment]
> 네, 말씀주신것처럼, `find` 함수로도 구현 가능한 부분이지만, `find` 와 달리, 탐색을 위한 `callback` 을 제공하지않고, `단순 값`으로 사용할 수 있게 추가한 함수입니다. 🤔

@mohwa 단순 값을 search할 필요가 없다는 말이였어요. 예시에 보면 3이라는 값을 찾기위해 인자값으로 3을 넣는데, 그럼 찾는값도 3이겠죠?
그렇다는 뜻은 사용자가 이미 search 할 값 "3"이라는것을 알고있다는 것인데, 굳이 search라는 함수를 사용해서 "3"이라는 값을 찾아야하나
 이것이 질문입니다
```javascript
search(['1', 2, 3], 3); // 3
```

**Comment by mohwa** [comment]
@seongdohee 네, 말씀주신 질문의 의도는 알고 있었는데요, 제가 생각하는 search함수를 사용하는 케이스중 하나는 이렇지않을까? 합니다. 🤔 

> 어떤 데이터에서 사용자가 input 한 값을 찾아야할 경우,(검색창을 생각하면 이해가 쉬울듯합니다) 😁

**Comment by seongdohee** [comment]
이 이슈는 #8 로 넘기고 close하겠습니다

**Comment by seongdohee** [comment]
> ### search
> 아래의 예시를 보면 두번째 인자로 필요한 값을 가지고있는데, 굳이 search를 할 필요가 없습니다.
> 이 함수를 사용하려면 사용자는 이미 search한 값을 알고있어야 합니다.
> 실제 검색기능을 구현하려면 `find` or `includes`을 사용하면 될 것 같습니다.
> 
> ```js
> search(['1', 2, 3], 3); // 3
> ```

이 이슈때문에 재오픈합니다. 아무리 생각해도 param과 return 값이 같아서 `search`라는 함수가 필요 없을것 같습니당.
@mohwa @prorice @eunjeongsong @sangheon-kim 의견 부탁드려요 🙏🏻

**Comment by mohwa** [comment]
@seongdohee ,

`search` 함수는 `deprecated` 하는것이 좋을듯합니다.

**Comment by mohwa** [comment]
@seongdohee ,

> 이 이슈때문에 재오픈합니다. 아무리 생각해도 param과 return 값이 같아서 search라는 함수가 필요 없을것 같습니당.

큰 차이는 아니지만, `includes` 와 `search` 는 이런 부분에서 차이가 있네요, 🤔 

> 반환값에 차이로 생길 수 있는 부분입니다.

```javascript
const arr = [1, 2, 3];
const inputValue = 3;

// ******************************
// includes 함수를 사용할 경우
// ******************************
if (includes(arr, inputValue)) {
  vm.searchedValue = inputValue;
}
// or
vm.searchedValue = includes(arr, inputValue) ? inputValue : '';


// ******************************
// search 함수를 사용할 경우
// ******************************
// template 에 할당할 경우, 보통 undefined 를 빈 문자열로 캐스팅하기때문에, 아래 OR 연산자도 필요없을 수 있습니다.
vm.searchedValue = search(arr, inputValue);
// or
vm.searchedValue = search(arr, inputValue) || ''
```

# 추가 차이

`findIndex` 와 `searchIndex` 는, 전달받는 arguments(`callback` or `값`) 에 차이가 있습니다.

`deepFind` 와 `deepSearch` 도, 전달받는 arguments(`callback` or `값`) 에 차이가  있습니다.

cc: @sangheon-kim

**Comment by seongdohee** [comment]
@mohwa 넵 차이점은 분명히 있지만 그것과 별개로 `search`가 있어야 하는 이유를 모르겠습니다 ㅠㅠ
결과값이 없을때 undefined return 하는 것은 array에서 inputValue 값이 있는지 없는지 찾을 때 유용할 수 있겠는데 결국 `includes`가 하는일과 같아서요.. 



```javascript
vm.searchedValue = search(arr, inputValue) || '';

// 결국 이것과 같지않나요? 
vm.searchedValue = inputValue || '';
```

**Comment by mohwa** [comment]
@seongdohee ,

위에서 언급한것처럼, 반환값이 `boolean` 이냐, 아님 `찾은 값` 이냐에 따라 조금 달라질듯합니다.

> 큰 차이는 아니지만, 아래처럼, 사용성에 영향이 있을 수 있는 부분이라 생각합니다.

- 즉, 상황에 따라 사용할 수 있도록 유지하는것이 좋을듯합니다 ~ 🚀 

```javascript
const arr = [1, 2, 3];
const inputValue = 3;

// ******************************
// includes 함수를 사용할 경우
// ******************************
// includes 에서 반환받은값은 boolean 유형이기때문에, 이 경우, 직접 사용할 수 없습니다.
vm.searchedValue = includes(arr, inputValue) ? inputValue : '';


// ******************************
// search 함수를 사용할 경우
// ******************************
// template 에 할당할 경우, 보통 template 엔진이 undefined 를 빈 문자열로 캐스팅 후, 사용합니다.
vm.searchedValue = search(arr, inputValue);
```

**Comment by seongdohee** [comment]
@mohwa 메신저로 의논드렸지만서도 그렇다면 `search`라는 이름이 적절하지 않은것 같아요

1. findValue
2. searchValue
3. includesValue
4. findByValue
5. etc...

적절한 이름 투표받습니다. 다른 의견도 좋구요 모두 의견을 모아주세요 🙏🏻

**Comment by mohwa** [comment]
@seongdohee,

하나만 선택해야한다면,

`findByValue`

하나 이상 선택가능하다면,

`includesValue`, `findByValue`

해봅니다 ~ 🤒

**Comment by mohwa** [comment]
필요없겠다,

이름만 바꾸면 되겠다.

은정: findByValue
도희: findByValue
장현: findByValue


search 가 findByValue 로 바뀌면서, 기존 searchIndex, deepSearch 함수 이름도 다시 생각해봐야할듯하다.

**Comment by mohwa** [comment]
`search`, `searchIndex`, `deepSearch` 함수가 제거되어, 이 이슈를 Close 합니다.

> 라이브러리가 좀 더 간결해지기위해, 불필요하다 판단했습니다.
